# Generated by Django 4.0.3 on 2022-03-27 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('unique_code', models.CharField(default=None, max_length=8, unique=True)),
                ('image', models.ImageField(upload_to='images/<django.db.models.fields.CharField>')),
                ('rating', models.IntegerField()),
                ('web_site', models.CharField(max_length=40, null=True)),
                ('contact_phone', models.CharField(max_length=15, null=True)),
                ('characteristics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('type_of_location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('minimum_num_people', models.IntegerField()),
                ('reservation_recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
